chore (docs) Update contibuter docs to mention that DCO signoff is mandatory
openebs/website pull request #325
Opened 2022-07-12 09:09 UTC by abhilashshetty04

Signed-off-by: Abhilash Shetty <abhilash.shetty@datacore.com>

Update contibuter docs to mention that DCO signoff is mandatory

2022-07-15 17:41 UTC, niladrih requested changes
nit: Link should be an absolute one

2022-07-15 17:41 UTC, niladrih commented on CONTRIBUTING.md
> +We use the Developer Certificate of Origin (DCO) as an additional safeguard for the OpenEBS project. This is a well established and widely used mechanism to assure contributors have confirmed their r
```suggestion
We use the Developer Certificate of Origin (DCO) as an additional safeguard for the OpenEBS project. This is a well established and widely used mechanism to assure contributors have confirmed their right to license their contribution under the project's license. Please read [developer-certificate-of-origin](https://github.com/openebs/openebs/blob/HEAD/contribute/developer-certificate-of-origin).
```

2022-07-16 01:49 UTC, pawanpraka1 approved these changes
Looks good.

2022-07-16 15:02 UTC, closed without merging

2022-07-17 18:42 UTC, niladrih commented
These changes are handled in PR #328 .