fixed an error in setting mount parameters
openebs/website pull request #429
Opened 2024-04-19 02:40 UTC by waitstory

Field 'mountOptions'' is under the 'parameters'' field, an error will be reported when creating a StorageClass, so this problem needs to be fixed.

2024-04-19 05:48 UTC, waitstory commented
@avishnu Whether this question should be merged

2024-04-20 13:00 UTC, niladrih requested changes
Changes look good to me @waitstory! But, you'd have to DCO sign your commit before we can merge it.

If you're using the `git` CLI command, these commands should fix the problem for you.
```
git commit --amend -s --no-edit
git push -f
```

If you've not set your name and email on your git config, you'd need to do that before this works.
```
git config --global user.name "<your-name>"
git config --global user.email "<your-email>"
```

2024-04-20 13:15 UTC, waitstory commented
Thanks for reminding me, it has been resubmitted. @niladrih

2024-04-20 13:28 UTC, niladrih approved these changes

2024-04-20 13:28 UTC, merged